api_platform:
    title: Sentraider API
    version: 1.0.0

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
        multipart: ['multipart/form-data']

    # Format
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
        image:    ['image/*']
        multipart: ['multipart/form-data']

    # Activation graphQl
    graphql:
        graphiql:
            enabled: true

    # Authorization bearer jwt
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
