api_platform:
    title: Sentraider API
    version: 1.0.0

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']

    # Activation graphQl
    graphql:
        graphiql:
            enabled: true

    # Authorization bearer jwt
    swagger:
        versions: [3]

    #Format
    formats:
        jsonld:  ['application/ld+json']
        jsonhal: ['application/hal+json']
        xml:     ['application/xml', 'text/xml']
        json:    ['application/json']
        yaml:    ['application/x-yaml']
        csv:     ['text/csv']
        html:    ['text/html']


        api_keys:
            apiKey:
                name: Authorization
                type: header