<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVLJYjtB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVLJYjtB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVLJYjtB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVLJYjtB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVLJYjtB\App_KernelDevDebugContainer([
    'container.build_hash' => 'VLJYjtB',
    'container.build_id' => '23afdb88',
    'container.build_time' => 1586781656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVLJYjtB');
