<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container76u5Qw8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container76u5Qw8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container76u5Qw8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container76u5Qw8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container76u5Qw8\App_KernelDevDebugContainer([
    'container.build_hash' => '76u5Qw8',
    'container.build_id' => 'af6ad151',
    'container.build_time' => 1600872567,
], __DIR__.\DIRECTORY_SEPARATOR.'Container76u5Qw8');
